// Battle setup and flow: bag -> battlefield, camera, intro fly-in, start/finish, rewards.
'use strict';
// Bag -> battle. The rules live in Sim.createBattle (scripts/battle-sim.js); this snapshots the bag into plain data
// for it and adds what only the view needs (listener, effect lists, deploy grid, camera, intro).
function buildBattle(){
 const seed=Math.floor(Math.random()*4294967296);
 const groupData=groups().map(g=>({type:g.type,aff:g.aff,pieces:g.pieces.map(pp=>({id:pp.id,cells:pieceIdx(pp),power:powerOf(pp)}))}));
 const b=Sim.createBattle({seed,wave:state.wave,cols:state.cols,open:state.open,groups:groupData,cellPiece:state.board.map(p=>p&&!D[p.type].material?p.id:null)});
 const {sx,sy,cellPos}=b.layout;
 const cells=state.board.map((p,i)=>state.open[i]?{...cellPos(i),color:p&&!D[p.type].material?AFF[p.aff].color:null}:null).filter(Boolean);
 for(const u of b.units)u.phase=Math.random()*6.28;
 return Object.assign(b,{listener:battleView,started:performance.now(),fx:[],parts:[],shake:0,damage:[],label:null,grid:{cells,sx,sy},intro:null,cam:{x:W/2,y:H/2,s:1}});}
// Camera: zoom in on a small army, pull out as the army (or the melee) spreads.
function fitBox(list){if(!list.length)return {x:W/2,y:H/2,s:1};let x0=Infinity,x1=-Infinity,y0=Infinity,y1=-Infinity;for(const u of list){const sz=u.boss?76:u.type==='golem'?57:43;x0=Math.min(x0,u.x-sz*.5);x1=Math.max(x1,u.x+sz*.5);y0=Math.min(y0,u.y-sz);y1=Math.max(y1,u.y+14);}const w=Math.max(150,x1-x0+56),h=Math.max(190,y1-y0+56);return clampCam({x:(x0+x1)/2,y:(y0+y1)/2,s:Math.max(1,Math.min(2,W/w,H/h))});}
function clampCam(c){const vw=W/c.s/2,vh=H/c.s/2;c.x=Math.max(vw,Math.min(W-vw,c.x));c.y=Math.max(vh,Math.min(H-vh,c.y));return c;}
function updateCamera(dt){const b=battle;if(!b||!b.cam)return;let list=b.units.filter(u=>u.hp>0);if(b.intro&&b.intro.t<.8)list=list.filter(u=>u.team===0);const t=fitBox(list),k=1-Math.exp(-dt*(b.intro?3.4:1.8));b.cam.s+=(t.s-b.cam.s)*k;b.cam.x+=(t.x-b.cam.x)*k;b.cam.y+=(t.y-b.cam.y)*k;clampCam(b.cam);}
function worldToScreen(x,y){const r=$('canvas').getBoundingClientRect(),k=r.width/W,c=battle.cam;return {x:r.left+((x-c.x)*c.s+W/2)*k,y:r.top+((y-c.y)*c.s+H/2)*k,k:k*c.s};}
// Bag → battlefield transition: each piece flies from its bag cell to its starting spot.
function flyIn(starts){const layer=document.createElement('div');layer.className='flyLayer';document.body.appendChild(layer);let longest=0;
 for(const u of battle.units){if(u.team!==0)continue;const r0=starts[u.cell];if(!r0)continue;const im=images[imgFor(u)];if(!im)continue;const sz=u.type==='golem'?57:u.type==='slime'?35:39,ih=sz*im.height/im.width,box=(stickerRigs[u.type]||u.type==='slime')?unitSpriteMetrics(u,im):{dw:sz,h:ih,x:-sz/2,by:15-ih},e=worldToScreen(u.x,u.y),ew=box.dw*e.k,eh=box.h*e.k,ecx=e.x+(box.x+box.dw/2)*e.k,ecy=e.y+(box.by+box.h/2)*e.k;
  const scx=r0.left+r0.width/2+(u.slots>1?(u.slot-(u.slots-1)/2)*r0.width*.3:0),scy=r0.top+r0.height/2,s0=Math.min(r0.width/ew,r0.height/eh)*(u.slots>1?.75:.9);
  layer.insertAdjacentHTML('beforeend',pic(u));const el=layer.lastElementChild;el.style.cssText+=`;left:${ecx-ew/2}px;top:${ecy-eh/2}px;width:${ew}px;height:${eh}px;transform:translate(${scx-ecx}px,${scy-ecy}px) scale(${s0})`;
  const delay=Math.floor(u.cell/state.cols)*45+u.slot*25;longest=Math.max(longest,delay);el.dataset.delay=delay;}
 void layer.offsetWidth;for(const el of layer.children){el.style.transition=`transform .56s cubic-bezier(.3,.75,.25,1) ${el.dataset.delay}ms`;el.style.transform='none';}
 setTimeout(()=>{layer.remove();if(battle&&battle.intro)battle.intro.fly=false;beep(420,.06);},longest+600);}
function advanceIntro(d){const i=battle.intro;i.t+=d;if(i.t>=i.dur&&!i.fly){battle.intro=null;$('battleLabel').textContent=battle.boss?'보스 출현 · 군단의 힘을 보여주세요':'군단 출전!';setTimeout(()=>{if(mode==='battle'&&!paused)$('battleLabel').textContent='';},1500);beep(280,.15);}}
function startBattle(){if(mode!=='prepare'||!totalCount())return;closeModal();save();{const enc=encounter();let nf=0;for(const o of enc.list)if(noteCodex('foe',o.type))nf++;if(enc.boss&&noteCodex('foe','boss'+state.wave))nf++;if(nf)setTimeout(()=>toast(`도감 등록 +${nf}`),900);}const starts={};document.querySelectorAll('#board .cell').forEach(el=>{const im=el.querySelector('img:not(.aff)');if(im)starts[+el.dataset.i]=im.getBoundingClientRect();});
 mode='battle';paused=false;speed=1;$('pause').textContent='Ⅱ';$('speed').textContent='1×';battle=buildBattle();$('battleRound').textContent=`${state.wave} / 12`;$('battleLabel').textContent='가방 진형 그대로 전개';render();fitMobile();
 const allies=battle.units.filter(u=>u.team===0);battle.cam=fitBox(allies);battle.intro={t:0,dur:1.6,fly:true};renderArmy();if(window.__TEST__){battle.intro=null;return;}flyIn(starts);}
function renderArmy(){const alive={};for(const u of battle.units)if(u.team===0&&u.pid&&u.hp>0)alive[u.pid]=(alive[u.pid]||0)+1;$('army').innerHTML=battle.pieceList.map(pc=>{const n=alive[pc.pid]||0;return `<div class="armyItem ${n?'':'dead'}" data-pid="${pc.pid}"><span class="ring"></span>${pic({type:pc.type,aff:pc.aff})}<span class="cnt">×${n}</span></div>`;}).join('');updateRings();}
function ringOf(pc){if(pc.type==='mage')return 1-Math.max(0,pc.skillCd)/8;const us=battle.units.filter(u=>u.pid===pc.pid&&u.hp>0);if(!us.length)return 0;return us.reduce((a,u)=>a+Math.max(0,Math.min(1,1-u.cd*u.rate)),0)/us.length;}
function updateRings(){if(!battle||mode!=='battle')return;for(const pc of battle.pieceList){const el=$('army').querySelector(`[data-pid="${pc.pid}"]`);if(!el)continue;el.style.setProperty('--p',Math.round(ringOf(pc)*100));el.classList.toggle('pulse',battle.time-pc.pulse<.6);}}
function battleReport(){const by=battle.stats.by,list=battle.pieceList.map(pc=>({pc,...(by[pc.pid]||{dmg:0,kills:0,skills:0})})),score=x=>x.dmg+x.kills*20+x.skills*30,total=list.reduce((a,x)=>a+x.dmg,0),mvp=list.slice().sort((a,b)=>score(b)-score(a))[0];if(!mvp||total<1)return '';const heat=new Map();for(const x of list)for(const i of x.pc.cells)heat.set(i,x);const grid=state.open.map((o,i)=>{const x=heat.get(i);return `<i class="${o?'o':''} ${x&&x===mvp?'mvp':''}" ${x?`style="--h:${Math.min(1,Math.max(.12,x.dmg/total*2.4)).toFixed(2)}"`:''}></i>`;}).join('');const chains=list.reduce((a,x)=>a+x.skills,0);return `<div class="report"><span class="heat">${grid}</span><div><b>MVP · ${D[mvp.pc.type].name}</b><small>피해 ${Math.round(mvp.dmg)} (${Math.round(mvp.dmg/total*100)}%) · 처치 ${mvp.kills} · 발동 ${mvp.skills}</small><small>연쇄 발동 ${chains}회${battle.stats.weak?` · 약점 적중 ${battle.stats.weak}회`:''} · 가방이 붉을수록 기여가 큽니다</small></div></div>`;}
function finishBattle(won){if(mode!=='battle')return;const round=state.wave,final=round===12,earned=round%4===0?12:6+Math.floor((round-1)/4);if(won){state.wins++;state.gold+=earned;state.status=final?'cleared':round%4===0?'reward':'between';}else state.status='defeated';save();modal(`<h2>${won?(final?'군단 원정 완료!':'승리!'):'원정 종료'}</h2><div class="resultArmy">${groups().slice(0,5).map(g=>pic({type:g.type,aff:g.aff})).join('')}</div>${battleReport()}<p>${won?(final?'세 지역의 보스를 모두 물리쳤습니다.':'백팩에서 만든 군단이 승리를 가져왔습니다.'):(battle.time>=60?'제한 시간 60초가 지났습니다.':'아군이 모두 쓰러졌습니다.')}</p><div class="badges"><span class="badge">${round} / 12전</span><span class="badge">처치 ${battle.stats.kills}</span><span class="badge">${Math.floor(battle.time)}초</span>${won?`<span class="badge">+${earned}G</span>`:''}</div><p class="small">${won?'모든 몬스터가 다음 전투에 완전한 체력으로 출전합니다.':'다음 원정에서 무리의 크기와 전열·후방 구성을 바꿔 보세요.'}</p><button class="action" data-action="${won&&!final?(round%4===0?'bossReward':'next'):'restart'}">${won&&!final?(round%4===0?'보스 보상 선택':'상점으로 돌아가기'):'새 원정 시작'}</button>`);beep(won?660:160,.22);}
function nextRound(){state.wave++;state.rerolls=0;state.status='playing';mode='prepare';battle=null;selected=state.board.find(p=>p&&!D[p.type].material)?.id||null;makeShop();closeModal();save();render();}
function bossReward(){modal(`<h2>보스 특별 보상</h2><p>군단의 다음 방향을 선택하세요.</p><button class="reward" data-reward="slimes">${pic({type:'slime'})}<span><b>슬라임 피스 ×2</b><small>빈칸 2개 필요 · 전투 슬라임 4마리 추가</small></span></button><button class="reward" data-reward="gold">${pic({type:'fire'})}<span><b>골드 +10G</b><small>다음 상점에서 원하는 빌드에 투자</small></span></button><button class="reward" data-reward="expand">${pic({type:'golem'})}<span><b>${BAGS[state.bag].steps[state.grown||0]?'백팩 확장':'골드 +12G'}</b><small>${BAGS[state.bag].steps[state.grown||0]?`잠긴 칸 ${BAGS[state.bag].steps[state.grown||0].length}개 해방`:'최대 크기 보유 보상'}</small></span></button><button class="reward" data-reward="cursed">${pic({type:'curse'})}<span><b>골드 +18G · 저주</b><small>저주 조각(2칸)이 가방에 들어옵니다 · 정화 4G</small></span></button>`);}
function claimReward(kind){if(state.status!=='reward')return;if(kind==='slimes'){const sa=piece('slime'),sb=piece('slime');if(!stash(sa))return toast('빈칸이 부족합니다. 다른 보상을 선택하세요');if(!stash(sb)){state.pieces=state.pieces.filter(x=>x!==sa);state.bench=state.bench.map(x=>x===sa?null:x);rebuild();return toast('빈칸이 부족합니다. 다른 보상을 선택하세요');}}else if(kind==='gold')state.gold+=10;else if(kind==='expand'){if(!expand())state.gold+=12;}else if(kind==='cursed'){const cp=piece('curse');if(!stash(cp))return toast('저주 조각을 둘 자리가 없습니다. 다른 보상을 선택하세요');state.gold+=18;}else return;nextRound();}
