// Codex, menu and next-fight preview overlays.
'use strict';
const CODEX_AFF=[['fire','불꽃 정수'],['water','물의 정수'],['poison','독버섯'],['life','생명 정수'],['steam','불꽃 + 물'],['plague','독 + 생명'],['blast','불꽃 + 독'],['spring','물 + 생명']];
function codexHTML(){const row=(ok,img,name,desc)=>`<div class="cx ${ok?'':'lock'}">${img}<span><b>${ok?name:'???'}</b><small>${ok?desc:'아직 발견하지 못했습니다'}</small></span></div>`;
 const aff=CODEX_AFF.map(([k,f])=>row(codex.aff[k],pic({type:'slime',aff:k}),AFF[k].name.trim()+' 무리',`${AFF[k].effect}<br>${f}${RECIPES[k]?'':''}`)).join('');
 const fuse=Object.entries(FUSE).map(([k,t])=>row(codex.fuse[t],pic({type:t}),D[t].name,k.split('+').map(x=>D[x].name).join(' + ')+' → 실패 없는 변이')).join('');
 const foes=Object.entries(ENEMY).map(([k,E])=>row(codex.foe[k],pic({type:k}),E.name,`HP ${D[k].hp} · ATK ${D[k].atk}${D[k].range>60?' · 원거리':''}<br>${E.weak?'약점 '+ELN[E.weak]:''}${E.res?' · 저항 '+ELN[E.res]:''}`)).join('')+Object.entries(BOSS).map(([w,B])=>row(codex.foe['boss'+w],pic({type:B.type}),'👑 '+B.name,B.desc)).join('');
 const n=o=>Object.keys(o).length,tot=CODEX_AFF.length+Object.keys(FUSE).length+Object.keys(ENEMY).length+Object.keys(BOSS).length,got=CODEX_AFF.filter(([k])=>codex.aff[k]).length+Object.values(FUSE).filter(t=>codex.fuse[t]).length+Object.keys(ENEMY).filter(k=>codex.foe[k]).length+Object.keys(BOSS).filter(w=>codex.foe['boss'+w]).length;
 return `<h2>도감 ${got}/${tot}</h2><p class="small">변이·합성·조우로 채워집니다. 도감은 새 원정을 시작해도 유지됩니다.</p><div class="cxh">속성 변이 ${CODEX_AFF.filter(([k])=>codex.aff[k]).length}/${CODEX_AFF.length}</div>${aff}<div class="cxh">합성 정수 ${Object.values(FUSE).filter(t=>codex.fuse[t]).length}/${Object.keys(FUSE).length}</div>${fuse}<div class="cxh">적 도감 ${Object.keys(ENEMY).filter(k=>codex.foe[k]).length+Object.keys(BOSS).filter(w=>codex.foe['boss'+w]).length}/${Object.keys(ENEMY).length+Object.keys(BOSS).length}</div>${foes}<button class="action" data-action="close">닫기</button>`;}
function menu(){modal(`<h2>메뉴</h2><button class="reward" data-action="menuCodex"><span style="font-size:26px">📖</span><span><b>도감</b><small>발견한 속성·합성·적</small></span></button><button class="reward" data-action="menuHelp"><span style="font-size:26px">❔</span><span><b>도움말</b><small>게임 방법</small></span></button><button class="reward" data-action="askRestart"><span style="font-size:26px">🔄</span><span><b>새 원정</b><small>현재 원정을 초기화합니다</small></span></button><button class="action secondary" data-action="close">닫기</button>`);}
function foeHTML(){const enc=encounter(),adv=foeAdvice(enc);return `<h2>${enc.boss?'⚠ 보스전 예고':'다음 전투 예고'} · ${state.wave}/12</h2>${enc.boss?`<div class="foeRow boss">${pic({type:enc.boss.type})}<span><b>${enc.boss.name}</b><small>${enc.boss.desc}</small><small>HP ${enc.boss.hp} · ATK ${enc.boss.atk}</small><small>약점 ${ELN[ENEMY[enc.boss.type].weak]||'-'}${ENEMY[enc.boss.type].res?' · 저항 '+ELN[ENEMY[enc.boss.type].res]:''}</small></span></div>`:''}${enc.list.map(o=>{const E=ENEMY[o.type];return `<div class="foeRow">${pic({type:o.type})}<span><b>${E.name} ×${o.count}${o.units>o.count?` (${o.units}마리)`:''}</b><small>HP ${D[o.type].hp} · ATK ${D[o.type].atk}${D[o.type].range>60?' · 원거리':''}</small><small>${E.weak?'약점 '+ELN[E.weak]:''}${E.res?' · 저항 '+ELN[E.res]:''}</small></span></div>`;}).join('')}<div class="badges"><span class="badge">추천 ${ELN[adv.best]} (약점 ${adv.bestN}마리)</span><span class="badge">내 군단 약점 적중 가능 ${adv.hits}/${adv.total}</span>${adv.bad?`<span class="badge warn">저항당함 ${adv.bad}마리</span>`:''}</div><p class="small">약점 속성 공격은 피해 ×1.5, 저항은 ×0.5입니다. 고블린·마법사 같은 원거리 적을 먼저 노려 보세요.</p><button class="action" data-action="close">확인</button>`;}
function renderFoe(){const enc=encounter(),adv=foeAdvice(enc),el=$('foe'),near=!enc.boss&&state.wave%4===3;el.innerHTML=enc.list.map(o=>`<span class="fe">${pic({type:o.type})}<small>${o.count}</small></span>`).join('')+(enc.boss?`<span class="fe boss">${pic({type:enc.boss.type})}<small>👑</small></span>`:'')+`<span class="fm ${adv.hits?'on':''}">${adv.hits?'약점 적중 '+adv.hits:'약점 없음'}</span>`+(enc.boss?'<span class="warnb">👑 보스전</span>':near?'<span class="warnb">⚠ 다음은 보스전</span>':'')+'<span class="chev">›</span>';el.classList.toggle('boss',!!enc.boss||near);}
const SKILLD={skeleton:'쓰러져도 한 번 부활(체력 30%)',orc:'공격이 주변 적에게 번짐',mage:'8초마다 자신·인접 피스에 보호막',goblin:'인접 아군이 쓰러지면 일제 사격',slime:'쓰러지면 독 폭발'};
let codex={aff:{},fuse:{},foe:{}};try{const c=JSON.parse(localStorage.getItem('monster-backpack-codex'));if(c&&typeof c==='object')codex={aff:c.aff||{},fuse:c.fuse||{},foe:c.foe||{}};}catch(e){}
function noteCodex(kind,key){if(codex[kind][key])return false;codex[kind][key]=1;try{localStorage.setItem('monster-backpack-codex',JSON.stringify(codex));}catch(e){}return true;}
