// Prepare screen: shop, bench, board rendering, drag/select, mutation and fusion.
'use strict';
function bagSelect(){const mini=B=>`<span class="mini">${B.open0.map((o,i)=>`<i class="${o?'o':''} ${B.kinds[i]?'k-'+B.kinds[i]:''}"></i>`).join('')}</span>`;modal(`<h2>가방을 고르세요</h2><p class="small">가방 모양과 특수 칸이 이번 원정의 전략을 정합니다.</p>${Object.entries(BAGS).map(([id,B])=>`<button class="reward" data-bag="${id}">${mini(B)}<span><b>${B.name}</b><small>${B.desc}</small><small>시작: ${B.start.map(a=>D[a[0]].name).join(' · ')}</small></span></button>`).join('')}`);}
function infoCompact(i=selectedIndex(),preview=null){const bp=i<0?state.bench.find(q=>q&&q.id===selected):null,p=state.board[i]||bp;
 const wrap=(ic,h,chips,line)=>`<div class="ci"><div class="ico">${ic}</div><div class="it"><h3>${h}</h3><div class="chips">${chips}</div><p>${line}</p></div><span class="exp">⌄</span></div>`;
 if(!p)return wrap(pic({type:'slime'}),'작은 가방, 커다란 군단',`<span>총 ${totalCount()}마리</span>`,'피스를 눌러 선택하세요 · 끌어서 옮깁니다');
 const d=D[p.type];
 if(d.curse)return wrap(pic(p),d.name,'<span>공간 차지</span>','정화하려면 4G가 필요합니다');
 if(d.material)return wrap(pic(p),d.name,`<span>${d.gives?'합성 재료':'변이 재료'}</span>`,d.gives?AFF[d.gives].effect:'몬스터 무리에 올려 변이 · 재료끼리 붙이면 합성');
 const g=bp?{pieces:[p],cells:[],count:d.count}:groupAt(i),pw=powerOf(p),a=preview||p.aff,b=bonus(g.pieces.length),aff=AFF[a];
 const chips=`<span>×${g.count}</span><span>HP ${Math.round(d.hp*b.hp*pw.hp)}</span><span>ATK ${Math.round(d.atk*b.atk*pw.atk)}</span>`+pw.tags.slice(0,2).map(t=>`<span class="buff">${tagText(t)}</span>`).join('')+(bp?'<span>벤치</span>':'');
 const line=(a==='none'?d.role+(b.hp>1?` · 무리 HP +${Math.round((b.hp-1)*100)}%`:''):aff.effect)+(auraDesc(p)?` · ◆ ${auraDesc(p)}`:'')+(SKILLD[p.type]?` · ✦ ${SKILLD[p.type]}`:'');
 return wrap(pic({...p,aff:a}),`${aff.name}${d.name}${g.count>d.count?' 무리':''}`,chips,line);}
function infoPanel(i,preview){return infoOpen?infoHTML(i,preview)+'<span class="exp">⌃</span>':infoCompact(i,preview);}
function infoHTML(i=selectedIndex(),preview=null){const bp=i<0?state.bench.find(q=>q&&q.id===selected):null,p=state.board[i]||bp;if(!p){return `<div class="swarm">${pic({type:'slime'})}</div><div><h2>작은 가방, 커다란 군단</h2><p class="stats">총 ${totalCount()}마리 출전 준비</p><p class="infodesc">같은 몬스터를 붙이고<br>재료를 무리에 올려 변이시키세요.</p></div>`;}
 const d=D[p.type];if(d.gives)return `<div class="swarm" style="display:grid;place-items:center">${pic(p)}</div><div><h2>${d.name}</h2><div class="tags"><span class="tag">합성 재료</span><span class="tag">무리 전체 적용</span></div><p class="infodesc">${AFF[d.gives].effect}<br>몬스터 무리에 실패 없이 변이시킵니다.</p></div>`;if(d.curse)return `<div class="swarm" style="display:grid;place-items:center">${pic(p)}</div><div><h2>${d.name}</h2><div class="tags"><span class="tag">${shapeOf('curse').length}칸</span><span class="tag">공간 차지</span></div><p class="infodesc">아무 효과 없이 가방을 차지합니다.<br>정화하려면 4G가 필요합니다.</p></div>`;if(d.material)return `<div class="swarm" style="display:grid;place-items:center">${pic(p)}</div><div><h2>${d.name}</h2><div class="tags"><span class="tag">변이 재료</span><span class="tag">무리 전체 적용</span></div><p class="infodesc">선택 후 몬스터를 누르거나<br>몬스터 위로 끌어 놓으세요.</p><p>기본 변이 100% · 복합 변이 50%</p></div>`;
 const g=bp?{pieces:[p],cells:[],count:D[p.type].count}:groupAt(i),pw=powerOf(p),a=preview||p.aff,b=bonus(g.pieces.length),aff=AFF[a],count=g.count;let swarm='';for(let k=0;k<Math.min(count,10);k++){const cols=count>4?3:2;swarm+=pic({...p,aff:a}).replace('style="',`style="left:${8+(k%cols)*25}%;top:${count<=2?24:8+Math.floor(k/cols)*25}px;z-index:${k};animation-delay:${k*.12}s;`);}
 return `<div class="swarm">${swarm}</div><div><h2>${aff.name}${d.name}${count>d.count?' 무리':''}</h2><div class="tags"><span class="tag color" style="background:${aff.color};color:#2c241e">출전 ×${count}</span><span class="tag">연결 ${g.pieces.length}개</span>${shapeOf(p.type).length>1?`<span class="tag">${shapeOf(p.type).length}칸</span>`:''}${pw.tags.map(t=>`<span class="tag buff">${tagText(t)}</span>`).join('')}${bp?'<span class="tag">벤치 · 전투 불참</span>':''}</div><p class="stats">HP ${Math.round(d.hp*b.hp*pw.hp)} · ATK ${Math.round(d.atk*b.atk*pw.atk)}${pw.rate>1?` · 속도 ×${pw.rate.toFixed(2)}`:''} <small>/ 마리</small></p><p class="infodesc">${a==='none'?d.role+' · '+(b.hp>1?`무리 HP +${Math.round((b.hp-1)*100)}%`:'무리 보너스 없음'):aff.effect}${auraDesc(p)?`<br>◆ ${auraDesc(p)}`:''}${SKILLD[p.type]?`<br>✦ ${SKILLD[p.type]}`:''}</p></div>`;}
function render(){requestAnimationFrame(fitMobile);const prep=mode==='prepare';$('prepare').hidden=!prep;$('battle').hidden=prep;if(!prep)return;$('round').textContent=`${state.wave} / 12`;$('gold').textContent=`● ${state.gold}G`;$('region').innerHTML=`${Math.ceil(state.wave/4)}지역 · <b>${state.wave%4===0?'보스전':`${(state.wave-1)%4+1}번째 전투`}</b>`;$('info').className='skin info '+(infoOpen?'open':'compact');$('info').innerHTML=infoPanel();const soon=new Set((BAGS[state.bag].steps[state.grown||0]||[]).map(([x,y])=>y*state.cols+x));
 const map=new Map();groups().forEach(g=>g.cells.forEach(i=>map.set(i,g)));$('board').style.gridTemplateColumns=`repeat(${state.cols},1fr)`;
 const fus=fusableCells();$('board').innerHTML=state.board.map((p,i)=>{const g=map.get(i);let edges='';if(g&&g.pieces.length>1){const c=state.cols,contains=n=>g.cells.includes(n),t=contains(i-c)?0:3,b=contains(i+c)?0:3,l=i%c>0&&contains(i-1)?0:3,r=i%c<c-1&&contains(i+1)?0:3;edges=`<span class="group-wash"></span><span class="group-edge" style="border-width:${t}px ${r}px ${b}px ${l}px"></span>`;}let host=false,big='',pe='';if(p){const pc=pieceIdx(p),sh=shapeOf(p.type,p.rot);host=pc[0]===i;if(sh.length>1){const c=state.cols,has=n=>pc.includes(n),t=has(i-c)?0:2,b2=has(i+c)?0:2,l=i%c>0&&has(i-1)?0:2,r=i%c<c-1&&has(i+1)?0:2;pe=`<span class="pwash"></span><span class="pedge" style="border-width:${t}px ${r}px ${b2}px ${l}px"></span>`;if(host){const bw=Math.max(...sh.map(a=>a[0]))+1,bh=Math.max(...sh.map(a=>a[1]))+1;big=pic(p,'big').replace('style="',`style="left:calc(${-sh[0][0]}*(100% + 3px));top:0;width:calc(${bw}*100% + ${(bw-1)*3}px);height:calc(${bh}*100% + ${(bh-1)*3}px);`);}}}
 const lock=!state.open[i],kind=cellKind(i);return `<button class="cell ${fus.has(i)?'fusable':''} ${p&&p.id===selected?'selected':''} ${big?'host':''} ${lock?'lock':''} ${lock&&soon.has(i)?'soon':''} ${kind?'k-'+kind:''}" data-i="${i}" style="--group:${g?AFF[g.aff].color:'#999'}" aria-label="${i+1}번 칸 ${lock?'잠김':p?D[p.type].name:'빈칸'}">${kind&&!lock?`<span class="kg">${KIND[kind].g}</span>`:''}${edges}${pe}${p&&p.id===selected?auraArrows(p,i):''}${p&&host?(big||pic(p))+(D[p.type].count===2?'<span class="count">×2</span>':'')+(p.aff!=='none'?`<img class="aff" src="${ASSETS[p.aff==='fire'||p.aff==='steam'||p.aff==='blast'?'fire':p.aff==='poison'||p.aff==='plague'?'poison':'water']}" alt="속성">`:''):''}</button>`;}).join('');
 renderBench();renderFoe();$('shop').innerHTML=state.shop.map((o,i)=>`<button class="skin cardSkin offer" data-offer="${i}" ${o.sold?'disabled':''}>${o.sold?'':`<span class="pin ${o.pinned?'on':''}" data-pin="${i}" title="리롤해도 유지">📌</span>`}${pic({type:o.type})}<strong>${D[o.type].name}</strong><span class="price">● ${D[o.type].cost}G${shapeOf(o.type).length>1?` · ${shapeOf(o.type).length}칸`:''}</span>${o.sold?'<span class="sold">구매 완료</span>':''}</button>`).join('');$('reroll').textContent=`리롤 ${rerollCost()}G ↻`;$('reroll').disabled=state.gold<rerollCost();$('fight').disabled=totalCount()===0;const p=selectedPiece(),onB=!!p&&state.bench.includes(p);$('sell').disabled=!p||(p&&D[p.type].curse&&state.gold<4);$('rotate').disabled=!(p&&shapeOf(p.type).length>1);$('stow').disabled=!p;const rl=$('bwrap').classList.contains('rail');$('stow').textContent=onB?(rl?'⇦ 꺼내기':'⇧ 꺼내기'):(rl?'⇨ 보관':'⇩ 보관');$('sell').textContent=p?(D[p.type].curse?'정화 -4G':`🗑 판매 +${Math.floor(D[p.type].cost/2)}G`):'판매';$('rotate').hidden=!(p&&shapeOf(p.type).length>1);$('acts').style.visibility=p?'visible':'hidden';$('instruction').textContent=!p?`${state.board.filter(Boolean).length} / ${state.open.filter(Boolean).length}칸 · ${totalCount()}마리`:D[p.type].curse?'저주 조각 · 정화하면 비워집니다':D[p.type].material?'무리를 탭해 변이 · 재료끼리 붙이면 합성':onB?'가방 빈칸을 탭하면 꺼냅니다':'빈칸을 탭하거나 끌어서 이동';}
function renderBench(){const B=BAGS[state.bag].bench;$('bench').innerHTML=B.map((k,i)=>{const p=state.bench[i];return `<button class="bslot ${k==='mat'?'mat':''} ${p&&p.id===selected?'selected':''}" data-b="${i}" aria-label="보관 ${i+1} ${p?D[p.type].name:'빈 슬롯'}">${p?pic(p):`<span class="bl">${k==='mat'?'⚗':'＋'}</span>`}</button>`;}).join('')+'<button class="bslot trash" id="sellSlot" aria-label="판매">🗑</button>';}
function stowTo(p,k){Rules.stowTo(state,p,k);selected=p.id;save();render();beep(460,.04);}
function stow(){if(mode!=='prepare'||!$('overlay').hidden)return;const p=selectedPiece();if(!p)return;if(state.bench.includes(p)){if(!Rules.takeFromBench(state,p))return toast('가방에 들어갈 자리가 없습니다');selected=p.id;save();render();return;}const j=Rules.benchSlotFor(state,p);if(j<0)return toast('벤치에 빈 슬롯이 없습니다');stowTo(p,j);}
function benchTap(k){if(mode!=='prepare'||!$('overlay').hidden)return;const sp=selectedPiece(),q=state.bench[k];if(q){selected=q.id;render();return;}if(sp){if(!benchOK(k,sp))return toast('재료만 보관할 수 있는 슬롯입니다');stowTo(sp,k);}}
function unbenchAt(p,i){if(Rules.unbenchAt(state,p,i)){selected=p.id;save();render();beep(520,.04);return;}toast('그 자리에는 들어가지 않습니다');}
function togglePin(i){if(mode!=='prepare'||!Rules.togglePin(state,i))return;save();render();}
function buy(i){if(mode!=='prepare')return;const r=Rules.buy(state,i);if(!r.ok){if(r.reason==='gold')toast('골드가 부족합니다');else if(r.reason==='space')toast('가방과 벤치에 자리가 없습니다. 판매하거나 재배치해 보세요');return;}selected=r.piece.id;if(r.onBench)toast('가방이 가득 차 벤치에 보관했습니다');save();render();beep(580,.05);}
function rerollCost(){return Rules.rerollCost(state);}
function reroll(){if(mode!=='prepare'||!Rules.reroll(state).ok)return;save();render();beep(340,.04);}
function selectCell(i){if(mode!=='prepare'||!$('overlay').hidden||!state.open[i])return;const sp=selectedPiece(),q=state.board[i];if(sp&&state.bench.includes(sp)&&!q){unbenchAt(sp,i);return;}if(sp&&state.pieces.includes(sp)&&q&&q!==sp&&D[sp.type].material&&D[q.type].material&&fusionResult(selectedIndex(),i)){offerFusion(selectedIndex(),i);return;}if(sp&&state.pieces.includes(sp)&&q!==sp&&D[sp.type].material&&q&&!D[q.type].material){offerMutation(selectedIndex(),i);return;}if(sp&&!q&&state.pieces.includes(sp)){const from=Rules.relocateFrom(state,sp,i);if(from>=0){move(from,i);return;}toast('그 자리에는 들어가지 않습니다');return;}selected=q?q.id:null;render();}
function move(from,to){if(mode!=='prepare'||from===to)return;const p=state.board[from];if(!p||to<0||to>=state.board.length)return;const r=Rules.move(state,from,to);if(r.kind==='mutation'){offerMutation(from,to);return;}if(r.kind==='fusion'){offerFusion(from,to);return;}if(r.kind==='fail'){render();return toast('자리가 맞지 않습니다');}
 selected=p.id;save();render();if(r.linked){toast('무리가 연결되었습니다!');beep(740,.08);}}
function rotate(){if(mode!=='prepare'||!$('overlay').hidden)return;const p=selectedPiece();if(!p)return;const r=Rules.rotate(state,p);if(r.status==='bench'){save();render();return;}if(r.status==='same'){if(r.changed)save();return toast('회전해도 모양이 같은 피스입니다');}if(r.status==='ok'){save();render();beep(520,.04);return;}toast('회전할 공간이 부족합니다');}
function mutationResult(source,target){return Rules.mutationResult(state,source,target);}
function fusionResult(i,j){return Rules.fusionResult(state,i,j);}
function offerFusion(i,j){const r=fusionResult(i,j);if(!r)return toast('합성할 수 없는 재료 조합입니다');const a=state.board[i],b=state.board[j],d=D[r.type];modal(`<h2>재료 합성</h2><div class="preview">${pic(a)}<span class="arrow">＋</span>${pic(b)}<span class="arrow">→</span>${pic({type:r.type})}</div><p><b>${d.name}</b></p><p>${AFF[d.gives].effect}</p><div class="badges"><span class="badge">성공률 100%</span><span class="badge">재료 2개 소비</span></div><p class="small">합성한 정수는 몬스터 무리에 실패 없이 변이시킵니다.</p><div class="two"><button class="action secondary" data-action="close">취소</button><button class="action" data-action="confirmMutation">합성하기</button></div>`);modalCallback=()=>applyFusion(i,j,r);}
function applyFusion(i,j,r){if(mode!=='prepare')return;const np=Rules.applyFusion(state,i,j,r);if(!np)return;selected=np.id;closeModal();const fresh=noteCodex('fuse',r.type);save();render();toast(`${D[r.type].name} 합성 완료${fresh?' · 도감 등록!':''}`);beep(760,.1);}
function fusableCells(){return Rules.fusableCells(state);}
function offerMutation(source,target){const r=mutationResult(source,target);if(!r)return toast('이 조합은 합성할 수 없습니다. 같은 속성은 중복 적용되지 않아요');const p=state.board[target],g=groupAt(target),material=state.board[source];modal(`<h2>${r.chance===1?'무리 변이':'복합 변이 도전'}</h2><div class="preview">${pic(p)}<span class="arrow">＋</span>${pic(material)}<span class="arrow">→</span>${pic({...p,aff:r.aff})}</div><p><b>${AFF[r.aff].name}${D[p.type].name} ×${g.count}</b></p><p>${AFF[r.aff].effect}</p><div class="badges"><span class="badge">성공률 ${r.chance*100}%</span>${r.still?'<span class="badge">증류 칸 +25%</span>':''}<span class="badge">재료 1개 소비</span></div><p class="small">${r.chance===1?'연결된 피스 전체가 변이합니다. 분리해도 속성은 유지됩니다.':'실패하면 재료만 사라집니다. 현재 무리와 속성은 유지됩니다.'}</p><div class="two"><button class="action secondary" data-action="close">취소</button><button class="action" data-action="confirmMutation">변이하기</button></div>`);modalCallback=()=>applyMutation(source,target,r);}
function applyMutation(source,target,r){if(mode!=='prepare')return;const res=Rules.applyMutation(state,source,target,r);if(!res)return;let nw=false;if(res.success){nw=noteCodex('aff',r.aff);selected=res.target.id;}closeModal();save();render();$('board').classList.remove('mutateFlash');void $('board').offsetWidth;$('board').classList.add('mutateFlash');toast(res.success?`${AFF[r.aff].name}무리 완성! ×${res.count}${nw?' · 도감 등록!':''}`:'변이 실패 · 재료만 소모되었습니다');beep(res.success?880:180,.14);}
function sell(){const p=selectedPiece();if(!p||mode!=='prepare')return;const {curse,value:val,blocked}=Rules.sellInfo(state,p);if(blocked)return toast('정화하려면 4G가 필요합니다');modal(`<h2>${curse?'저주 정화':'피스 판매'}</h2><div class="preview">${pic(p)}</div><p>${curse?'저주 조각을 <b>4G</b>를 내고 정화합니다.':`${AFF[p.aff].name}${D[p.type].name} 피스 1개를 <b>${val}G</b>에 판매합니다.`}</p><p class="small">${curse?'정화하면 차지하던 칸이 비워집니다.':'연결된 무리는 남은 피스를 기준으로 다시 계산됩니다.'}</p><div class="two"><button class="action secondary" data-action="close">취소</button><button class="action" data-action="confirmSell">${curse?'정화':'판매'}</button></div>`);modalCallback=()=>{Rules.applySell(state,p);selected=null;closeModal();save();render();};}
